Update nzoth.md
yuripiratello/wow-raid-plan pull request #1
Opened 2020-09-18 03:31 UTC by Nicolasteiji

Correções gramaticais

2020-09-18 14:49 UTC, brunogfranca requested changes

2020-09-18 14:49 UTC, brunogfranca commented on bfa/nyalotha/nzoth.md
> +Usa um neck no final da fase vunerável do boss
vulnerável*

2020-09-18 14:49 UTC, brunogfranca commented on bfa/nyalotha/nzoth.md
> +- Seta os 5 ultimos soaks com imunity pros adds e NAO BATE NELES
últimos

2020-09-19 01:02 UTC, brunogfranca approved these changes
LGTM

2020-09-19 01:17 UTC, yuripiratello approved these changes

2020-09-19 01:17 UTC, merged